### ISSUE TITLE
libprotobuf.so not generated

### ISSUE THREAD

**Issue by tomasreimers** [invokr/protobuf-emscripten#2]
I ran the instructions in https://github.com/invokr/protobuf-emscripten/commit/d515e619f6c159dd8cdb56688cda06ab5111272c (b/c I can't find any instructions on the readme of the latest branch), and it does not generate a .so anymore, rather it generates a collection of .a / .la / .dylib . 

Could you please update the readme to specify how we can use this with the latest patch?

Thanks so much,
Tomas

**Comment by invokr** [comment]
Hey,

I'll look into updating the repo with better instructions and a real Readme, also providing a Protobuf 3.0 version patch.

The .so suffix is only used on Linux. Windows uses .dll (not relevant in this case) and OS X uses .dylib. Try linking the .dylib into your emscripten project, that should do the trick.

Rob
