### ISSUE TITLE
Instructions to build on a Windows system?

### ISSUE THREAD

**Issue by birgersp** [invokr/protobuf-emscripten#5]
Hi,

Current build instructions appears to be UNIX-only. Is it complicated to port to build on Windows?
I tried building it using Ubuntu and I got the following files which I've copied:

![image](https://user-images.githubusercontent.com/5260237/28382077-2cd65a62-6cbd-11e7-8580-2fcf32dd4226.png)

Can I use these files to build my WebAssembly project?

**Comment by invokr** [comment]
You can try linking the .so (which should be emscripten bytecode if you've build it under linux) with emscripten in windows. But then again, I'm not sure if emscripten bytecode is cross-os compatible even if you are running the same versions.

There is a tutorial for setting up emscripten on windows here: http://kripken.github.io/emscripten-site/docs/building_from_source/building_emscripten_from_source_on_windows.html

IMHO it's not worth the effort you'll have to put into it. If you desperately need protobuf javascript support, there are javascript-only libraries out there.

**Comment by birgersp** [comment]
Gave it another go, and I was wrong, it works (my mistake). So yes the `.so` file can be renamed and linked with emscripten in Windows. Thanks a lot for this, @invokr !
