### ISSUE TITLE
Can't compile with library

### ISSUE THREAD

**Issue by janhartman** [invokr/protobuf-emscripten#6]
Hi,
I managed to build protobuf (version 3.5.1) with emscripten, but when I try to compile my program (which has the line `#include "google/protobuf/util/time_util.h"` in it), emcc throws `fatal error: 'google/protobuf/util/time_util.h' file not found`.

I'm linking the compiled `libprotobuf.a` (tried with `libprotobuf.so` too, tried renaming both to `.bc` too, neither option worked) by doing: `emcc -s WASM=1 -o out.html program.cpp libprotobuf.bc`.

Have you had any similar issues or is there something I'm doing wrong?

**Comment by invokr** [comment]
First of all, like it says in the readme, you should rename the `.so` so `.bc` and link that one. The `.a` is irrelevant in the whole process.

As for your issue: I've not come across it and so far the only supported 3x version in the repo is 3.1.0. The newer protobuf versions have a javascript target out of the box. 

Did you properly specify the include directory with `-I`? A correct example for invoking emscripten would be: `em++ -Iprotobuf-emscripten/3.1/src program.cpp libprotobuf.bc`.

**Comment by janhartman** [comment]
I have renamed the `.so` to `.bc`, but the output is still the same. (Specified the include directory too).
Thanks for helping, sorry to have wasted your time.

**Comment by invokr** [comment]
The `.so` to `.bc` will only solve the linking issue which would occur if the the file had the `.so` ending. You are not getting to the linking step which is why there is no difference. A missing include already aborts everything way before linking happens.

I don't mind helping you get it working if you tell me your rough use-case and how you build the 3.5.1 protobuf with emscripten in the first place. Not sure if applying the 3.1 patches is enough. Posting the `CFLAGS` and `LDFLAGS` would help, too.

**Comment by janhartman** [comment]
I'm actually trying to compile [grpc](https://github.com/grpc/grpc) to WebAssembly  to get a C++-based grpc client working in the browser (it seems like a long shot...). 

I managed to build protobuf 3.5.1 with `emconfigure ./configure --with-protoc=protoc && emmake make`, this produces the library files under `src/.libs/`.

I realize now that the issue I talked about is not in the linking, but in the preprocessing. Sorry for the trouble, I do not have a lot of experience with compiling C/C++. It seems to find the headers now, but then I still get an error, described [here](https://github.com/google/protobuf/issues/4122). Do you have any ideas on how to fix this?

**Comment by invokr** [comment]
You can't compile the standard protobuf with emscripten. The sole purpose of this repository is to provide a patched version of protobuf (right now 2.6 and 3.1) that compiles with emscripten. The original google version will not compile with emscripten.

As for GRPC: Sorry to tell you that won't work either. At least not without knowing a substantial amount of C++. From what I can tell at first glance, it uses low level networking (e.g. http/2 protocl implementation on top of unix sockets) and threading. None of those are supported in emscripten. You could write your own transport layer but the threading issue would require a huge amount of changes to the code.

**Comment by janhartman** [comment]
That's too bad - well now it makes sense why there are no proper implementations of gRPC for browsers. I think I'll have to stick with REST/JSON and use a reverse REST - GRPC proxy. Thanks for all the help!
